openapi: 3.0.3
info:
  title: Todo App API
  description: OpenAPI specification for a simple todo list app.
  version: 1.0.0
servers:
  - url: "http://localhost:8080/api/v1"
    description: Development
paths:
  /todos:
    get:
      summary: Retrieves the entire list of todo items.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/todoItem"
    post:
      summary: Creates a new todo item.
      requestBody:
        description: The todo item to create.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/todoItem"
        required: true
      responses:
        201:
          description: The todo item was created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/todoItem"
        400:
          description: The request to create the todo item is not valid.
  /todos/{id}:
    get:
      summary: Retrieves a todo item by its ID.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/todoItem"
        404:
          description: No todo item exists with the given ID.
    put:
      summary: Replaces a todo item.
      responses:
        200:
          description: The todo item was replaced.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/todoItem"
        400:
          description: The request to replace the todo item is not valid.
        404:
          description: No todo item exists with the given ID.
    patch:
      summary: Updates a todo item.
      responses:
        200:
          description: The todo item was updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/todoItem"
        400:
          description: The request to update the todo item is not valid.
        404:
          description: No todo item exists with the given ID.
    delete:
      summary: Deletes a todo item.
      responses:
        200:
          description: The todo item was deleted.
        404:
          description: No todo item exists with the given ID.
    parameters:
      - name: id
        in: path
        description: The ID of a todo item.
        required: true
        schema:
          type: integer
          minimum: 1
components:
  schemas:
    todoItem:
      type: object
      required:
        - summary
      properties:
        id:
          type: integer
          description: The todo item's ID.
          readOnly: true
          example: 1
        summary:
          type: string
          minLength: 1
          description: A brief summary of the todo.
          example: "Learn OpenAPI"
        created_at:
          type: string
          description: The time the todo item was created.
          readOnly: true
          example: "2022-06-12T12:34:56.789Z"
        updated_at:
          type: string
          description: The time the todo item was last updated.
          readOnly: true
          example: "2022-06-12T16:20:00.000Z"
